### PR TITLE
Added a 74LS238 3-Line to 8-Line Decoder/Demultiplexer

### PR DESCRIPTION
**Pull request by BobKuczewski**
These files were patterned after the 74LS138 already in the library.

### CODE REVIEW

**Comment by rileym65** [comment]
Please alter the descriptions in the menu files to indicate inverted outputs, then I will merge

**Comment by BobKuczewski** [comment]
OK. I'll look at it right now.

**Comment by BobKuczewski** [comment]
I'm not sure what the right term is. I am thinking of this:
74LS138 - 3-line to 8-line decoder, selected=0
74LS238 - 3-line to 8-line decoder, selected=1
But maybe I should use "active low" or "active high". What do you like?

**Comment by BobKuczewski** [comment]
Actually, I like these:

74LS138 - 3-line to 8-line decoder, selected=Low
74LS238 - 3-line to 8-line decoder, selected=High

What do you think?

**Comment by rileym65** [comment]
active low or active high is fine
    Mike

________________________________

**Comment by BobKuczewski** [comment]
Do I need to make another pull request?
I'm a little rusty on my GitHub protocols. :(

**Comment by rileym65** [comment]
That is fine
   Mike
________________________________

**Comment by rileym65** [comment]
Not sure, let me merge and see
________________________________

**Review by rileym65 — APPROVED** [review]

**Comment by BobKuczewski** [comment]
Thanks Mike!!

**Comment by rileym65** [comment]
Most welcome.  Feel free to submit pull request for any other changes you make.
    Mike
________________________________

**Pull request merged**
